version: '3'

services:
  app:
    build: .
    command: bash -c "yarn typeorm migration:run && yarn dev:server"
    networks:
      - default
      - app-connect
    ports:
      - '3333:3333'

    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: 'users'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'ms-user'
    networks:
      - app-connect
    ports:
      - '5433:5433'

networks:
  default:
  app-connect:
    internal: True
