version: '3'

services:
  app-user:
    build: .
    command: bash -c "yarn typeorm migration:run && yarn dev:server"
    networks:
      - default
      - app-connect-user
    ports:
      - '3334:3334'

    depends_on:
      - db-user

  db-user:
    image: postgres:12
    environment:
      POSTGRES_DB: 'users'
      POSTGRES_USER: 'ms-user'
      POSTGRES_PASSWORD: 'ms-user'
    networks:
      - app-connect-user
    ports:
      - '5432'

networks:
  default:
  app-connect-user:
    internal: True
