apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ms-user
  name: ms-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-user
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-user
    spec:
      containers:
        - image: gcr.io/learning-357114/ms-user:1.0.0
          name: ms-user
          resources: {}
          imagePullPolicy: Always
          ports:
            - name: defaut
              containerPort: 3333
              protocol: TCP
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            readinessProbe:
              httpGet:
                path: /healthcheck
                scheme: HTTP
                port: 80
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ms-user
  annotaitons:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: ms-user
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3333
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-cluster
  annotations:
    nginx.ingress.kubernetes.io/load-balance: ewma
spec:
  defaultBackend:
    service:
      name: ms-user
      port:
        number: 3333
  rules:
    - http:
        paths:
          - path: /user
            pathType: ImplementationSpecific
            backend:
              service:
                name: ms-user
                port:
                  number: 3333
