apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ms-user
  name: ms-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-user
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-user
    spec:
      containers:
        - image: gcr.io/learning-357114/ms-user:1.0.0
          name: ms-user
          resources: {}
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
              protocol: TCP
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: ms-user
  name: ms-user
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: service-port-grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
    - name: service-port-rest
      port: 3333
      protocol: TCP
      targetPort: 3333
  selector:
    app: ms-user
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-cluster
  annotations:
    nginx.ingress.kubernetes.io/load-balance: ewma
spec:
  rules:
    - http:
        paths:
          - path: /user
            pathType: ImplementationSpecific
            backend:
              service:
                name: ms-user
                port:
                  number: 3333
          - path: /cart
            pathType: Prefix
            backend:
              service:
                name: ms-cart
                port:
                  number: 3333
          - path: /product
            pathType: ImplementationSpecific
            backend:
              service:
                name: ms-catalog
                port:
                  number: 3333
          - path: /order
            pathType: ImplementationSpecific
            backend:
              service:
                name: ms-order
                port:
                  number: 3333
